name: Push to Azure Container Registry
on:
  push:
    branches:
      - main

jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USER_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker compose build

      - name: Push Docker image to Azure Container Registry
        run: |
          docker tag rolandomesagdp-api:latest ${{ secrets.ACR_LOGIN_SERVER }}/rolandomesagdp-api:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/rolandomesagdp-api:latest
